const dummyData = [
  {isbn10: 1234567890,
  isbn13: 1234567890123,
  category: "childrens",
  popularity: "some number????",
  title: "Green Eggs and Ham",
  author: "Dr. Seuss",
  imageURL: "https://images2.penguinrandomhouse.com/cover/9780394800165",
  priceHardcover: 100.99,
  pricePaperback: 10.99,
  priceAudio: 1.99,
  description: "With unmistakable characters and signature rhymes, Dr. Seuss’s beloved favorite has cemented its place as a children’s classic. Kids will love the terrific tongue-twisters as the list of places to enjoy green eggs and ham gets longer and longer...and they might even  learn a thing or two about trying new things!"},

{isbn10: 1234567890,
  isbn13: 1234567890123,
  category: "childrens",
  popularity: "some number????",
  title: "Yertle the Turtle",
  author: "Dr. Seuss",
  imageURL: "https://images2.penguinrandomhouse.com/cover/9780394900872",
  priceHardcover: 200.99,
  pricePaperback: 20.99,
  priceAudio: 2.99,
  description: "The Cat in the Hat is a 1957 children's book written and illustrated by the American author Theodor Geisel, using the pen name Dr. Seuss. The story centers on a tall anthropomorphic cat who wears a red and white-striped hat and a red bow tie. The Cat shows up at the house of Sally and her brother one rainy day when their mother is away."},

{isbn10: 1234567890,
  isbn13: 1234567890123,
  category: "childrens",
  popularity: "some number????",
  title: "Dr. Seuss's Book of Colors",
  author: "Dr. Seuss",
  imageURL: "https://images2.penguinrandomhouse.com/cover/9781524766184",
  priceHardcover: 300.99,
  pricePaperback: 30.99,
  priceAudio: 3.99,
  description: "This simple rhymed riff about color is illustrated with art from some of the most beloved—and colorful—works by Dr. Seuss, including The Cat in the Hat, Green Eggs and Ham, and One Fish Two Fish Red Fish Blue Fish. Great for the earliest reader, it is a perfect companion to Dr. Seuss concept books like Mr. Brown Can Moo! Can You?, The Shape of Me and Other Stuff, and Dr. Seuss's ABC. Nurture a love of reading—and of the many colorful characters created by Dr. Seuss—with this great new concept book for beginning readers!"},

{isbn10: 1234567890,
  isbn13: 1234567890123,
  category: "childrens",
  popularity: "some number????",
  title: "Dr. Seuss's A B C",
  author: "Dr. Seuss",
  imageURL: "https://images2.penguinrandomhouse.com/cover/9780385375160",
  priceHardcover: 400.99,
  pricePaperback: 40.99,
  priceAudio: 4.99,
  description: "From Aunt Annie's Alligator to Zizzer-Zazzer-Zuzz, this sturdy board book version of Dr. Seuss's ABC is now available in a bigger trim size. With Dr. Seuss as your guide, learning the alphabet is as fun and as funny as the feather on a Fiffer-feffer-feff!"},

{isbn10: 1234567890,
  isbn13: 1234567890123,
  category: "childrens",
  popularity: "some number????",
  title: "Fox in Socks",
  author: "Dr. Seuss",
  imageURL: "https://images2.penguinrandomhouse.com/cover/9780394800387",
  priceHardcover: 400.99,
  pricePaperback: 40.99,
  priceAudio: 4.99,
  description: "This rhyming romp includes chicks with bricks, chewy blue glue, a noodle eating poodle, and so much more! Just try to keep your tongue out of trouble! Seuss piles his the energetic rhymes into a mountain of hilarity that the whole family will enjoy. Rhyming has never been this fun!"},

{isbn10: 1234567890,
  isbn13: 1234567890123,
  category: "childrens",
  popularity: "some number????",
  title: "Hop on Pop",
  author: "Dr. Seuss",
  imageURL: "https://images2.penguinrandomhouse.com/cover/9780394800295",
  priceHardcover: 400.99,
  pricePaperback: 40.99,
  priceAudio: 4.99,
  description: "Full of short, simple words and silly rhymes, this book is perfect for reading alone or reading aloud with Dad!  The rollicking rythym will keep kids entertained on every page, and it's an especially good way to  show Pop some love on Father’s Day!"},

{isbn10: 1234567890,
  isbn13: 1234567890123,
  category: "childrens",
  popularity: "some number????",
  title: "How the Grinch Stole Christmas",
  author: "Dr. Seuss",
  imageURL: "https://images2.penguinrandomhouse.com/cover/9780394800790",
  priceHardcover: 400.99,
  pricePaperback: 40.99,
  priceAudio: 4.99,
  description: "Not since 'Twas the night before Christmas' has the beginning of a Christmas tale been so instantly recognizable. This heartwarming story about the effects of the Christmas spirit will grow even the coldest and smallest of hearts. Like mistletoe, candy canes, and caroling, the Grinch is a mainstay of the holidays, and his story is the perfect gift for readers young and old."}

]

export default dummyData;