### Register user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

### Login user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "userC@test.com",
    "password": "password"
}

# userA id = 60272dc32b562508c4a69a4a
# userB id = 60275a77860d8630b88f7ce6

### Disaply all bookclubs
GET http://localhost:3000/bookclub/all 

### Disaply bookclub by id
GET http://localhost:3000/bookclub/6027582d28408307a8103ee9 

### User joins a bookclub
POST http://localhost:3000/bookclub/join/6027582d28408307a8103ee9 
Content-Type: application/json

{
    "userId": "60275a77860d8630b88f7ce6"
} 

### User Leaves a bookclub
DELETE http://localhost:3000/bookclub/join/6027582d28408307a8103ee9 
Content-Type: application/json

{
    "userId": "60275a77860d8630b88f7ce6"
}

### User creates a bookclub
POST http://localhost:3000/bookclub
Content-Type: application/json

{
    "name": "Horror Manga Club",
    "description": "Club for manga horrors",
    "owner": "60272dc32b562508c4a69a4a"
}

