@baseUrl = http://localhost:3000

### Infos
@matthew = 602be49226e7f146247321c8
@jason = 602be49a26e7f146247321c9
@chris = 602be49f26e7f146247321ca
@shinan = 602be4b126e7f146247321cd
@cayla = 602be52e26e7f146247321cf


### Get all users
GET {{baseUrl}}/user/all

### Get all users that user are friends with
POST {{baseUrl}}/user/friends
Content-Type: application/json

{
    "userId": "{{matthew}}"
}

### Get all users that user are not friends with
POST {{baseUrl}}/user/newfriends
Content-Type: application/json

{
    "userId":"{{matthew}}"
}


### User adds a friend
POST {{baseUrl}}/user/friend
Content-Type: application/json

{
    "userId":"{{matthew}}",
    "friendId":"{{jason}}"
}


# "recommendation": {"summary":"","description":""}

### Update user info
PUT {{baseUrl}}/user/info
Content-Type: application/json

{
    "userId":"602bfb512b04728dd5f0fb51",
    "bookPreference": "Drama",
    "recommendation": {"summary":"1984 is far from perfect","description":"Those words keep sounding in my head since I read this book. Gosh, probably the most haunting not to mention frightening book I've ever read. 1984 should also be included in the horror genre."}
}

### Get user payment info
GET {{baseUrl}}/user/payment
Content-Type: application/json

{
    "userId":"{{matthew}}"
}

### User add new payment
POST {{baseUrl}}/user/payment
Content-Type: application/json

{
    "userId":"{{matthew}}",
    "cardNumber":123456789,
    "cardHolder":"Matthew",
    "cardCVC":343,
    "cardExpiredDate":"cardExpiredDateLol"
}

### User update payment
PUT {{baseUrl}}/user/payment
Content-Type: application/json

{
    "paymentID": "602bedcc9b1f2d4518f78bee",
    "userId":"{{matthew}}",
    "cardNumber":123456,
    "cardHolder":"Matthew Ming",
    "cardCVC":343,
    "cardExpiredDate":"cardExpiredDateLol"
}

### User delete payment
DELETE  {{baseUrl}}/user/payment
Content-Type: application/json

{
    "userId":"{{matthew}}"
}

### Get user sub info
GET  {{baseUrl}}/user/subscription
Content-Type: application/json

{
    "userId":"{{matthew}}"
}

### User joins a sub
POST  {{baseUrl}}/user/subscription
Content-Type: application/json

{
    "userId":"{{matthew}}",
    "name":"Pro",
    "description": "I like pro",
    "voucher": 1
}

### User cancels sub
DELETE   {{baseUrl}}/user/subscription
Content-Type: application/json

{
    "userId":"{{matthew}}"
}

### Get all books that the user owns
GET {{baseUrl}}/user/book
Content-Type: application/json

{
    "userId":"{{jason}}"
}

### User add book to library 7ef
POST  {{baseUrl}}/user/book
Content-Type: application/json

{
    "userId":"{{jason}}",
    "title":"Harry Potter",
    "authors":"JK Rowling",
    "isbn":525,
    "image":"https://media2.s-nbcnews.com/i/newscms/2020_26/3155921/191219-j-k-rowling-2018-ac-845p_b96cd21ada5eec6c9ff8b9ff33920b0f.jpg",
    "price":50,
    "category":"fiction"
}